# Generated by Django 3.0.7 on 2020-06-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='main_title',
        ),
        migrations.RemoveField(
            model_name='text',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='text',
            name='text_body',
        ),
        migrations.AddField(
            model_name='text',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='pub_date',
            field=models.DateField(verbose_name='publishing date'),
        ),
    ]
