# Generated by Django 3.0.8 on 2020-07-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200723_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportorder',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='server.Address'),
        ),
        migrations.AlterField(
            model_name='transportorder',
            name='pickup_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_address', to='server.Address'),
        ),
    ]
