# Generated by Django 3.0.8 on 2020-07-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_company_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('country_id', models.IntegerField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('street_no', models.IntegerField(blank=True, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('address_string', models.CharField(blank=True, max_length=255, null=True)),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.AddField(
            model_name='transportorder',
            name='auction_room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
