# Generated by Django 3.0.8 on 2020-07-20 08:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0003_auto_20200720_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_room_id', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_visible', models.BooleanField(blank=True, null=True)),
                ('is_open', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
