# Generated by Django 3.0.8 on 2020-07-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auctionroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionroom',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='auctionroom',
            old_name='user_id',
            new_name='user',
        ),
    ]
