# Generated by Django 3.0.8 on 2020-07-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20200720_1126'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auctionroom',
            table='auction_rooms',
        ),
    ]
