# Generated by Django 3.0.8 on 2020-07-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20200720_1155'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transportorder',
            table='transport_orders',
        ),
    ]
