# Generated by Django 3.0.8 on 2020-07-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20200720_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportorder',
            name='auction_room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.AuctionRoom'),
        ),
    ]
